FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY Services/UserService/UserService.Domain/UserService.Domain.csproj Services/UserService/UserService.Domain/
COPY Services/UserService/UserService.Application/UserService.Application.csproj Services/UserService/UserService.Application/
COPY Services/UserService/UserService.Infrastructure/UserService.Infrastructure.csproj Services/UserService/UserService.Infrastructure/
COPY Services/UserService/UserService.API/UserService.API.csproj Services/UserService/UserService.API/

RUN dotnet restore Services/UserService/UserService.API/UserService.API.csproj

COPY . .

RUN dotnet publish Services/UserService/UserService.API/UserService.API.csproj \
    -c Release \
    -o /app/publish \
    --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080

ENTRYPOINT ["dotnet", "UserService.API.dll"]