apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: localhost/ecommerce-payment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: SQL_PASSWORD
            - name: ConnectionStrings__PaymentDatabase
              value: "Server=172.30.110.203,1433;Database=ECommerce_PaymentDb;User Id=sa;Password=$(SQL_PASSWORD);TrustServerCertificate=True;MultipleActiveResultSets=true"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ecommerce
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP