apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: localhost/ecommerce-user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: SQL_PASSWORD
            - name: ConnectionStrings__UserDatabase
              value: "Server=172.30.110.203,1433;Database=ECommerce_UserDb;User Id=sa;Password=$(SQL_PASSWORD);TrustServerCertificate=True;MultipleActiveResultSets=true"
            - name: Jwt__SecretKey
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: JWT_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ecommerce
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
