FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY Services/ProductService/ProductService.Domain/ProductService.Domain.csproj Services/ProductService/ProductService.Domain/
COPY Services/ProductService/ProductService.Application/ProductService.Application.csproj Services/ProductService/ProductService.Application/
COPY Services/ProductService/ProductService.Infrastructure/ProductService.Infrastructure.csproj Services/ProductService/ProductService.Infrastructure/
COPY Services/ProductService/ProductService.API/ProductService.API.csproj Services/ProductService/ProductService.API/

RUN dotnet restore Services/ProductService/ProductService.API/ProductService.API.csproj

COPY . .

RUN dotnet publish Services/ProductService/ProductService.API/ProductService.API.csproj \
    -c Release \
    -o /app/publish \
    --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080

ENTRYPOINT ["dotnet", "ProductService.API.dll"]