FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY ApiGateway/ECommerce.ApiGateway.csproj ApiGateway/

RUN dotnet restore ApiGateway/ECommerce.ApiGateway.csproj

COPY . .

RUN dotnet publish ApiGateway/ECommerce.ApiGateway.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080

ENTRYPOINT ["dotnet", "ECommerce.ApiGateway.dll"]